name: password_manager
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+21

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  args: ^2.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_sticky_headers: ^2.0.2
  provider: ^6.0.0
  desktop_window: ^0.4.0
  path_provider: ^2.0.11
  flutter_widget_offset: ^1.1.0
  googleapis_auth: ^1.3.1
  googleapis: ^9.2.0
  intl: ^0.17.0
  url_launcher: ^6.1.5
  http: ^0.13.5
  _discoveryapis_commons: ^1.0.3
  logging: ^1.1.0
  pointycastle: ^3.6.2
  encrypt: ^5.0.1
  super_tag_editor: ^0.0.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
